# ---- Build Stage ----
FROM docker.m.daocloud.io/library/node:20-alpine AS build
WORKDIR /app

RUN apk add --no-cache git

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run docs:build

# ---- Serve Stage ----
FROM docker.m.daocloud.io/library/nginx:alpine
COPY nginx.local.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/docs/.vitepress/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
